---
name: Application CI Pipeline on Push
env:
  CONTAINER_IMAGE: pramanick1984/test1
on:
  push:
    branches: [master]

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and tag docker image
      run: |
         docker build . -t ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}
    - name: Publish docker image to dockerhub
      run: docker push ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}

    - name: Cloning Receiver Repo
      run: git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/goutamp/receiver.git"

    - name: Importing the GPG key
      run: |
        echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
      env:
        GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY_B64}}

    - name: Update tag in Receiver
      run: |
            git config --global user.email "pramanick.goutam@gmail.com"
            git config --global user.name "goutamp"
            git checkout -b feature/Updating-tag-sample1-ms-${GITHUB_SHA::7}
            docker run -v $PWD/kustomization.yaml:/app/kustomization.yaml k8s.gcr.io/kustomize/kustomize:v3.8.7 edit set image sample1-image=${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}
            git diff --exit-code && echo 'Already deployed' || \
            (git commit -S -am "Upgrade docker tag of sample1-service to ${GITHUB_SHA::7}" \
            && git push origin feature/Updating-tag-sample1-ms-${GITHUB_SHA::7} \
            && hub pull-request -m "feat:Updating tag for Sample service" -b master -h feature/Updating-tag-sample1-ms-${GITHUB_SHA::7} )
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}      
      working-directory: receiver/Services/base
